# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22f5619ff63e70fe7d38e79f60ca35a559b8ed34a659b9f583f281e436af4939a746243c2b87f58c6d1a58faa1a0e16f64c40a6aee9e6a376cd27a6cd81dd4d3

test:
  secret_key_base: 7ee369275bb1a3736fc7e37c34e2ca6a450270a91cbbf37e2978105c55bff1ac467de110816900a81ea065f204b2946f801c3e5c66999ceecf3032b1459bba17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
